<?php

namespace OseilleTest\Db\Layer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-12 at 14:36:16.
 */
class ScriptTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers \Oseille\Db\Layer\Script
     * @covers \Oseille\Db\Layer\AbstractLayer
     * @uses \Oseille\Db\Driver\Parameters\Parameters
     * @uses \Oseille\Db\Driver\Parameters\Credentials
     * @uses \Oseille\Db\Driver\Stub
     *
     * @expectedException \InvalidArgumentException
     */
    public function testReadInvalidArgumentException()
    {
        $pParameters = new \Oseille\Db\Driver\Parameters\Parameters();
        $pCredentials = new \Oseille\Db\Driver\Parameters\Credentials();
        $pDriver = new \Oseille\Db\Driver\Stub($pParameters, $pCredentials);
        $pLayer = new \Oseille\Db\Layer\Script($pDriver);

        $pLayer->load('');
    }

    /**
     * @covers \Oseille\Db\Layer\Script
     * @uses \Oseille\Db\Layer\AbstractLayer
     * @uses \Oseille\Db\Driver\Parameters\Parameters
     * @uses \Oseille\Db\Driver\Parameters\Credentials
     * @uses \Oseille\Db\Driver\Stub
     *
     * @expectedException \RuntimeException
     */
    public function testLoadRuntimeException()
    {
        $pParameters = new \Oseille\Db\Driver\Parameters\Parameters();
        $pCredentials = new \Oseille\Db\Driver\Parameters\Credentials();
        $pDriver = new \Oseille\Db\Driver\Stub($pParameters, $pCredentials);
        $pDriver->setExpectedExec(false);
        $pLayer = new \Oseille\Db\Layer\Script($pDriver);

        $sScript = APPLICATION_PATH_DATA . \DIRECTORY_SEPARATOR . 'nothing.sql';

        $pLayer->load($sScript, ['pbrDdb'], ['test'], true);
    }

    /**
     * @covers \Oseille\Db\Layer\Script
     * @uses \Oseille\Db\Layer\AbstractLayer
     * @uses \Oseille\Db\Driver\Parameters\Parameters
     * @uses \Oseille\Db\Driver\Parameters\Credentials
     * @uses \Oseille\Db\Driver\Stub
     */
    public function testLoad()
    {
        $pParameters = new \Oseille\Db\Driver\Parameters\Parameters();
        $pCredentials = new \Oseille\Db\Driver\Parameters\Credentials();
        $pDriver = new \Oseille\Db\Driver\Stub($pParameters, $pCredentials);
        $pDriver->setExpectedExec(0);
        $pLayer = new \Oseille\Db\Layer\Script($pDriver);

        $sScript = APPLICATION_PATH_DATA . \DIRECTORY_SEPARATOR . 'nothing.sql';

        $this->assertSame(0, $pLayer->load($sScript, ['pbrDdb'], ['test'], true));
    }
}
